### ISSUE TITLE
Module Creation

### ISSUE THREAD

**Issue by jonathanpli** [DumplingLTD/ExceptionNull#14]
Parsing of markdown into module display

**Comment by fru1tstand** [comment]
[Module Creation Design Doc](https://docs.google.com/document/d/1UF-DxG3bAwyF1-ZLiXPpuTi_hVukApvjvw6i8KC3Pf8)
[Module (Concept) Design Doc](https://docs.google.com/document/d/1tnRjUSGROF49kJKjjqT9ZSozI22j3HBpMVd9XvFbSjc)

**Comment by fru1tstand** [comment]
Deferred due to refocus on PvP.
